Ctvrta_hodina
DanielTheRam/Python pull request #4
Opened 2023-10-18 17:10 UTC by DanielTheRam

2023-10-23 05:44 UTC, JKafka97 requested changes

2023-10-23 05:44 UTC, JKafka97 commented on ctvrtahodina.py/knihovna.py
> +name = input("Napište svoje jméno ")
prvně si tu ukládej data do prom a až pak se ptej uživatele .. takhle je to nečitelné jak hell :D ... takže input až za všechno zapisování do prom.

2023-10-23 05:44 UTC, JKafka97 commented on ctvrtahodina.py/knihovna.py
> +users_books = {"Dekameron"}
tohle snad řeší borrowed_books ne? ... když je tam tvoje jméno tak jí máj půjčenou

2023-10-23 05:44 UTC, JKafka97 commented on ctvrtahodina.py/knihovna.py
> +        action = input("""Vyberte číslo operace, kterou chcete provést:
tohle tu nebude 1x pro admina a 1x pro usery ... jak jsem ti psal, tak když vypiš knihy zadá admin tak to vypíše všechny

2023-10-23 05:44 UTC, JKafka97 commented on ctvrtahodina.py/knihovna.py
> +# pokud si uživatel půjčí knihu, kterou poté vrátí, není odebrán ze seznamu půjčených knih
vyřeší se odebráním té users_books ne?

2023-10-25 18:07 UTC, DanielTheRam commented on ctvrtahodina.py/knihovna.py
> +name = input("Napište svoje jméno ")
vyřešeno

2023-10-25 18:07 UTC, DanielTheRam commented on ctvrtahodina.py/knihovna.py
> +users_books = {"Dekameron"}
vyřešeno

2023-10-25 18:07 UTC, DanielTheRam commented on ctvrtahodina.py/knihovna.py
> +        action = input("""Vyberte číslo operace, kterou chcete provést:
vyřešeno

2023-10-26 09:03 UTC, JKafka97 approved these changes

2023-10-26 09:03 UTC, merged